apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  namespace: jmedina
  labels:
    app: db
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 20
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: db-secret
        name: db-deployment
        image: harbor.dev.afsmtddso.com/jmedina-harbor-project/db@sha256:19da9d324aad6eb5246da4fc3cf3d79f6884de7a102a240184522f2466dbe25d
        ports:
        - containerPort: 5432
